version: '3.4'

services:
  grocerylistapi:
    image: ${DOCKER_REGISTRY-}grocerylistapi
    build:
      context: .
      dockerfile: GroceryListAPI/Dockerfile
    depends_on:
      - "pg-db"
  pg-db:
    container_name: pg-db
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
       - pg_volume:/var/lib/postgresql/data

volumes:
  pg_volume:
    external: true